### ISSUE TITLE
Expose superagent to perform it's configuration

### ISSUE THREAD

**Issue by inovakov** [visionmedia/supertest#202]
I would like to do something like this:

```
var agent = request.agent(app);
agent.superagent.parse['application/problem+json'] = agent.superagent.parse['application/json'];
```

It's not possible right now and I cannot use supertest for testing. I'll have to use superagent directly :(.

**Comment by janfabry** [comment]
https://github.com/yury-sannikov/supertest/commit/3e79c452f1bd2730a51ba9589a52cf934960a508 implements this, but no pull request was created yet.

**Comment by HolySamosa** [comment]
+1 please.

**Comment by gabegorelick** [comment]
Since this issue was closed, does that mean this was implemented? As far as I can tell, there's no way to pass in an instance of `superagent`, and the instance used by `supertest` is not exported. Am I missing how this can be done?

https://github.com/visionmedia/supertest/blob/910a11133b94d44f8ac380a8a46bfdab2bce9f19/lib/test.js#L7

**Comment by gabegorelick** [comment]
FYI, this is possible using `require.resolve`:
```js
const path = require('path');
const supertestPath = path.dirname(require.resolve('supertest'));
const superagentPath = require.resolve('superagent', {
    paths: [supertestPath]
});
const superagent = require(superagentPath);
```

It still would be nice for `supertest` to export this directly though. Especially since it already exports superagent's `Agent`:  https://github.com/visionmedia/supertest/pull/54
