### ISSUE TITLE
Suggestion: expectBody() with several variations

### ISSUE THREAD

**Issue by rprieto** [visionmedia/supertest#222]
For extra legibility, it would be nice if `supertest` supported checking for a particular field in the response body. This is what I've used so far:

``` js
request(server)
  .get('/api/foobar')
  .expect(404)
  .expect(property('error.message', 'Resource not found'))
  .end(done)

// implemented as
function property(path, value) {
  return function(res) {
    var have = res.body.should.have;
    have.propertyByPath.call(have, path.split('.')).eql(value);
  };
}
```

I think this could be nice to have built-in to `supertest`, for example:

```
.expect(404)
.expectBody('path.to.the.prop', value)
```

As a broader question, the single `expect()` method makes everything nice & easy. However it also means limited polymorphism. Maybe extra functions like `expectHeaders`, `expectBody`, etc would allow for several variants for each target:
- `expectHeaders(key)`, `expectHeader(key, value)`, `expectHeaders(map)`
- `expectBody(string)`, `expectBody(obj)`, `expectBody(path, value)`

Any thoughts?

**Comment by ThomWright** [comment]
`expectBodyHas(obj)` (or similar) would also be a nice alternative to `expectBody(path, value)`.

+1 for the suggestion.

In the meantime, I'll be pinching your implementation :)

**Comment by rprieto** [comment]
Actually, thinking of the current implementation... I'm wondering if another approach would be a nice set of matchers for `supertest`. For example

```js
let { status, header, bodyPath } = require('supertest-matchers');

request(server)
  .get('/api/foobar')
  .expect(status(404))
  .expect(header('content-type', 'application/json'))
  .expect(bodyPath('error.message', 'Resource not found'))
  .expect(bodyContains({ name: 'John', age: 30 }))
  .end(done);
```

This is still based on `expect()` accepting any function, and
- decouples them from nicely from supertest itself (similar to `grunt contrib` in a way)
- means matchers don't have to step on each other's toes / no need to decide if `expect(string, string)` should apply to matching headers or the body.

**Comment by ThomWright** [comment]
:+1: Agree, that's much nicer! I'd be happy to help implement it too.

**Comment by davesteinberg** [comment]
It's a real shame that this issue (and a few other related ones) have been closed over the years without explanation.

If there was some way of doing doing a fuzzy match on a response body object, I could use SuperTest without any additional assertion library. It's kind of amazing that there's a form of `expect()` to explicitly support testing response body objects, but it's basically useless (because there's always stuff in a response body that varies or isn't significant to the test). So, I end up using the function form of `expect()` as a hook for assertions using another library in almost all of the tests I write.

The suggestion here would vastly improve SuperTest.
