### ISSUE TITLE
res.body is not consistent depending on the 'Content-Type' header

### ISSUE THREAD

**Issue by JohnBerlin** [visionmedia/supertest#300]
Hello,

I'm having trouble for a small test which works perfectly with content type **'image/png'** but fails with **'audio/mpeg'**.

https://gist.github.com/JohnBerlin/0b598e34564631d49318

Tell me if I'm doing anything wrong
Thanks for your time

Forgot to attach the output :
```
$ npm test

> musique@1.0.0 test C:\Dev\musique
> mocha src/**/*_test.js



  file sending
    √ works for image/png (59ms)
    1) works for audio/mpeg


  1 passing (90ms)
  1 failing

  1) file sending works for audio/mpeg:
     Uncaught TypeError: Arguments must be Buffers
      at Function.compare (buffer.js:162:11)
      at Test.<anonymous> (C:\Dev\musique\src\api\gist_test.js:24:31)
      at Test.assert (C:\Dev\musique\node_modules\supertest\lib\test.js:156:6)
      at Server.assert (C:\Dev\musique\node_modules\supertest\lib\test.js:127:12)
      at emitCloseNT (net.js:1518:8)
```

**Comment by mikelax** [comment]
I think this is expected behavior based on superagent functionality. 
Here is the [superagent documentation](https://visionmedia.github.io/superagent/#parsing-response-bodies) relating to it's handling of responses based on Content-Type. 

You will have to add additional logic if you want a generic handler for different content-type responses.
