### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by kewgrz** [visionmedia/supertest#592]
I was hoping to use SuperTest for my API testing but there doesn't seem to have been any new updates for the last 6 months and has some pull requests.

**Comment by miguelpduarte** [comment]
Would also like to know this.

It seems a bit unmaintained, but I haven't been able to find other alternatives :/

**Comment by rimiti** [comment]
Hello everyone, 

Yes is it! You can check the last commits to see who are the active maintainers.

The main issue with supertest is the superagent outdated dependence. For the moment, superagent version cannot be updated because a pull request must be done on superagent to handle errors. 

Related PR (for more informations): 
https://github.com/visionmedia/supertest/pull/558

If you want to help us, do not hesitate to create this PR on superagent. After that I will be very happy to merge / update all current PRs.

Have a nice day.

**Comment by YasharF** [comment]
Is this PR on superagent the fix? https://github.com/visionmedia/superagent/pull/1468
Does this mean superagent can be upgraded to the latest version now?

**Comment by rimiti** [comment]
The prerelease v5.0.0-0 has been created.

Do not hesitate to the this one in your projects to be sure there are no regressions.
