### ISSUE TITLE
Error with functions using async/await

### ISSUE THREAD

**Issue by keligijus** [visionmedia/supertest#608]
It seems supertest and jest do not work well together when testing route functions that use `async/await`.

I've got a reproduction [repo](https://github.com/keligijus/supertest-async-bug) that shows the exact same cases, one with async/await, the other with regular promises. First always fails with `TypeError: res.send is not a function` while the latter works fine.

Here's a snippet of the failing test:
```js
describe("GET /test-async ", () => {
  const router = express.Router();
  app.use(router);

  test("stores the data", async () => {
    require("./routes")({ router, db });

    const response = await request(router).get("/test-async");

    expect(response.status).toBe(200);
  });
});
```

Here's the tested function:
```js
  router.get("/test-async", async (req, res) => {
    try {
      const result = await db.get();
      return res.send(result);
    } catch (err) {
      console.log(err);
      res.sendStatus(500);
    }
  });
```

Is it possible I've just made a mistake using supertest?

Here's the link to the reproduction https://github.com/keligijus/supertest-async-bug

**Comment by keligijus** [comment]
People having similar issues (and no clear solution) - https://github.com/visionmedia/supertest/issues/596 and https://github.com/visionmedia/supertest/issues/416

**Comment by jonathansamines** [comment]
@keligijus Supertest is not designed to test individual express Routers in isolation. It can use one of the following:

- An express application. In this case the library will automatically [autobind](https://expressjs.com/es/4x/api.html#app.listen) the application to an ephemeral port and then use the socket information to create a valid origin to which all requests are made to (using [superagent](https://visionmedia.github.io/superagent/).
- A valid URL. In this case, requests are made to the already provided URL by using the same mechanism outlined above.

Note that the first case, is just a convenience method for the second one, when you have an express application. Hope the above information helps.

**Comment by jonathansamines** [comment]
As additional information, the reason why your code is getting that exception is because an express router [is also](https://github.com/expressjs/express/blob/master/lib/express.js#L72) [a function](https://github.com/expressjs/express/blob/master/lib/router/index.js#L43) and therefore this library will try to use it as a [request listener](https://github.com/visionmedia/supertest/blob/master/index.js#L22), which means it will be invoked by the http module as indicated by it's [documentation](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener) but because the expected public API (the arguments) are not the same, it breaks in a completely unexpected way.

**Comment by keligijus** [comment]
Hey @jonathansamines, thanks very much for a detailed explanation. I've misunderstood how Supertest works. Strange why it failed differently when using async.

Thanks again! :)
