### ISSUE TITLE
Unable to downgrad the version 0.21.0 

### ISSUE THREAD

**Issue by anil826** [visionmedia/supertest#624]
I update the node version too v8.x.x and superagent version to the latest and then my old tests are going to fail. Then I try to revert the changes but every time I keep getting the version  `3.8.6`
I am using ` npm view superagent --version` to check I even install the package globally - `npm install -g  "https://github.com/visionmedia/superagent.git#0.21.0"`

**Comment by jonathansamines** [comment]
Until this module itself makes an upgrade to the superagent module (available on a beta), it is hard to force an specific version of a transitive dependency because this module will install it's own version of such library. You might want to try using the beta, or using a package-lock to force an specific version of the transitive dependency.

**Comment by anil826** [comment]
Thank @jonathansamines `package-lock` is fix the issue.
