### ISSUE TITLE
Release 5.0 as final version

### ISSUE THREAD

**Issue by caiquecastro** [visionmedia/supertest#627]
Is there an ETA to publish 5.0 as a final version?

**Comment by YasharF** [comment]
@rimiti thank you for the great work.  Do you think if you can mark 5.x as the latest version in npm's repo?  I didn't notice any issues in github about it since you pushed the early version last October.

```
$ npm outdated
Package    Current   Wanted  Latest
supertest  5.0.0-0  5.0.0-0   4.0.2
```

Better yet, may I suggest creating and pushing 5.1 or 6.0 as the latest version while:
- Dropping support for end-of-life versions of NodeJS (<10)?  Ref: https://github.com/visionmedia/supertest/blob/master/package.json#L16 and https://nodejs.org/en/about/releases
- Regenerating package-lock.json as well?  I suspect some of the deeper level dependencies may have updates to pick up.
