### ISSUE TITLE
Response can not access to array object in 6.2.4

### ISSUE THREAD

**Issue by Alex-Lin5** [visionmedia/supertest#783]
env: `Supertest 6.2.4`, `Windows 11 Pro 21H2, 22000.856`
### Description
`res.body` does give the whole object, but `res.body.solutions` does not give an object, it is undefined.

Code here
```
      const res = await request(server).get(root);
```
Log here
```
^      console.log('res get all:', res.body);

      res get all: [
        {
          _id: '62fc15a51aa9ad1b58f48f5e',
          description: '62fc15a51aa9ad1b58f48f55',
          solutions: [ '62fc15a51aa9ad1b58f48f5c' ],
          __v: 0
        },
        {
          _id: '62fc15a51aa9ad1b58f48f62',
          description: '62fc15a51aa9ad1b58f48f56',
          solutions: [ '62fc15a51aa9ad1b58f48f60' ],
          __v: 0
        }
      ]

^      console.log('res solutions,', res.body.solutions);

      res solutions, undefined
```
And my project is over here: https://github.com/Alex-Lin5/Algorithm-Coding-Pool

**Comment by Fishbowler** [comment]
Here, it looks like res.body is an array, not an object. Which res.body.solutions were you expecting it to return, the first one or the second one? Or both?

Since res.body is an array of two objects, you'd can access it a couple of ways.

Access via index:

console.log('first res solutions', res.body[0].solutions) //this should print `[ '62fc15a51aa9ad1b58f48f5c' ]`

Access via iterator:

res.body.forEach(obj -> console.log('a solution', obj.solutions)) //this should print both on separate lines

**Comment by Alex-Lin5** [comment]
Thanks man, I figured out where the bug is now.
